In [1]:
# Day 34: Feature Engineering and Data Preprocessing

print("Day 34 - Feature Engineering and Data Preprocessing")
print("Project: Smart House Price Predictor and Market Analysis")

Day 34 - Feature Engineering and Data Preprocessing
Project: Smart House Price Predictor and Market Analysis

In [2]:
import pandas as pd
import numpy as np

data = {
    "area_sqft": [800, 1000, 1200, 1500, 1800, 2000, 2200, 2500],
    "bedrooms": [2, 2, 3, 3, 3, 4, 4, 4],
    "bathrooms": [1, 2, 2, 2, 3, 3, 3, 4],
    "parking": [0, 1, 1, 1, 1, 2, 2, 2],
    "location": [
        "Cuttack", "Cuttack", "Bhubaneswar", "Bhubaneswar",
        "Puri", "Puri", "Berhampur", "Berhampur"
    ],
    "price": [
        2000000, 2500000, 3200000, 4000000,
        4800000, 5500000, 6200000, 7500000
    ]
}

df = pd.DataFrame(data)

# Add sample missing values for preprocessing practice
df.loc[2, "bathrooms"] = np.nan
df.loc[5, "parking"] = np.nan

display(df)

   area_sqft  bedrooms  bathrooms  parking     location    price
0        800         2        1.0      0.0      Cuttack  2000000
1       1000         2        2.0      1.0      Cuttack  2500000
2       1200         3        NaN      1.0  Bhubaneswar  3200000
3       1500         3        2.0      1.0  Bhubaneswar  4000000
4       1800         3        3.0      1.0         Puri  4800000
5       2000         4        3.0      NaN         Puri  5500000
6       2200         4        3.0      2.0    Berhampur  6200000
7       2500         4        4.0      2.0    Berhampur  7500000

In [3]:
print("Missing values before cleaning:")
print(df.isnull().sum())

df["bathrooms"] = df["bathrooms"].fillna(
    df["bathrooms"].median()
)

df["parking"] = df["parking"].fillna(
    df["parking"].median()
)

print("\nMissing values after cleaning:")
print(df.isnull().sum())

Missing values before cleaning:
area_sqft    0
bedrooms     0
bathrooms    1
parking      1
location     0
price        0
dtype: int64

Missing values after cleaning:
area_sqft    0
bedrooms     0
bathrooms    0
parking      0
location     0
price        0
dtype: int64

In [4]:
df["price_per_sqft"] = df["price"] / df["area_sqft"]

display(df[["area_sqft", "location", "price", "price_per_sqft"]])
print("Price per square foot feature created!")

   area_sqft     location    price  price_per_sqft
0        800      Cuttack  2000000     2500.000000
1       1000      Cuttack  2500000     2500.000000
2       1200  Bhubaneswar  3200000     2666.666667
3       1500  Bhubaneswar  4000000     2666.666667
4       1800         Puri  4800000     2666.666667
5       2000         Puri  5500000     2750.000000
6       2200    Berhampur  6200000     2818.181818
7       2500    Berhampur  7500000     3000.000000

Price per square foot feature created!

In [5]:
df_encoded = pd.get_dummies(
    df,
    columns=["location"],
    dtype=int
)

display(df_encoded.head())
print("Location encoding completed!")

,area_sqft,bedrooms,bathrooms,parking,price,price_per_sqft,location_Berhampur,location_Bhubaneswar,location_Cuttack,location_Puri
0,800,2,1.0,0.0,2000000,2500.000000,0,0,1,0
1,1000,2,2.0,1.0,2500000,2500.000000,0,0,1,0
2,1200,3,3.0,1.0,3200000,2666.666667,0,1,0,0
3,1500,3,2.0,1.0,4000000,2666.666667,0,1,0,0
4,1800,3,3.0,1.0,4800000,2666.666667,0,0,0,1

Location encoding completed!

In [6]:
df_encoded.to_csv(
    "day34_processed_house_prices.csv",
    index=False
)

print("Processed dataset saved successfully!")

Processed dataset saved successfully!

# Day 34 - Feature Engineering and Data Preprocessing

## Work Completed
- Created a sample house-price dataset.
- Identified missing values.
- Filled missing values using the median.
- Created a price-per-square-foot feature.
- Converted location names into numeric columns.
- Saved the processed dataset as a CSV file.

## Conclusion
Data preprocessing improves data quality, while feature engineering creates useful information for machine learning. The processed dataset is now better structured for model training. This notebook uses sample data for learning.